# services:
#   app:
#     build:
#     ports:
#       - "8000:8000"
#     depends_on:
#       - mysql

#     mysql:
#       image: mysql
#       ports:
#       - "3306:3306"
#       environment:
#         MYSQL_USER: 'root'
#         MYSQL_DATABASE: 'test1'
#         MYSQL_ROOT_PASSWORD: 'root'
#   volumes:
#     db_data:

# version: '3.1'

# services:

#   db:
#     image: mysql
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root

version: '3.8'  # specify a version for compatibility

services:
  app:
    build: .
    ports:
      - "8001:8000"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      # MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DB: test1

volumes:
  db_data: