services:
  app:
    build:
    ports:
      - "8000:8000"
    depends_on:
      - mysql

    mysql:
      image: mysql
      ports:
      - "3306:3306"
      environment:
        MYSQL_USER: 'root'
        MYSQL_DATABASE: 'test1'
        MYSQL_ROOT_PASSWORD: 'root'
  volumes:
    db_data: